_target_: src.models.mri_direct_module.MRI_Direct_LitModule

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.0005
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 10

net:
  _target_: src.utils.direct_adaptors.recurrentvarnet.recurrentvarnet_adaptor.RecurrentVarNetAdaptor
  num_steps: 12
  recurrent_hidden_channels: 128
  recurrent_num_layers: 4
  initializer_initialization: sense
  learned_initializer: true
  initializer_channels: [32, 32, 64, 64]
  initializer_dilations: [1, 1, 2, 4]
  initializer_multiscale: 3
  sensitivity_model:
    _target_: src.utils.direct.nn.unet.unet_2d.UnetModel2d
    in_channels: 2
    out_channels: 2
    num_filters: 8
    num_pool_layers: 4
    dropout_probability: 0.0


# compile model for faster training with pytorch 2.0
compile: false

criterions:
  mse:
    _target_: torch.nn.MSELoss
  ssim:
    _target_: src.models.components.losses.SSIMLoss
#
#criterion_2:
#    _target_: torch.nn.L1Loss


